version: '3'

services:
  node-server:
    container_name: node
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
    networks:
      - local-network
  db:
    container_name: mysql
    platform: linux/x86_64
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    ports:
      - "3308:3308"
    logging:
      driver: none
    networks:
      - local-network
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    env_file:
      - .env
    restart: always
    logging:
      driver: none
    ports:
      - "9090:90"
    environment:
      PMA_HOST: db
    networks:
      - local-network

networks:
  local-network:

volumes:
  db_data: